### ISSUE TITLE
Error after installing the plugin

### ISSUE THREAD

**Issue by mirelsol** [kanboard/plugin-gitlab-webhook#1]
I get this error: PHP Fatal error:  
Using $this when not in object context in /var/www/kanboard/plugins/GitlabWebhook/Plugin.php on line 15
I'm using php 5.3.3-7

**Comment by sadhar** [comment]
Hi,
I have the same problem.
PHP version  5.3.3
Kanboard version 1.0.23

Error 1:
  kanboard]#  php index.php
       PHP Fatal error:  Using $this when not in object context in /var/www/kanboard/plugins/GitlabWebhook/Plugin.php on line 15

Error 2:
GitlabWebhook]# php Plugin.php
PHP Fatal error:  Class 'Kanboard\Core\Plugin\Base' not found in /var/www/kanboard/plugins/GitlabWebhook/Plugin.php on line 9

**Comment by fguillot** [comment]
It's a PHP 5.3 compatibility issue, will be fixed soon.

**Comment by sadhar** [comment]
What is the compatible version, yet ?

**Comment by fguillot** [comment]
This issue have been fixed in the version 1.0.1: https://github.com/kanboard/plugin-gitlab-webhook/releases/tag/v1.0.1
