### ISSUE TITLE
fixed task

### ISSUE THREAD

**Issue by esclkm** [kanboard/plugin-gitlab-webhook#10]
at this moment there is no syntax analyzer
we can write : 
closed #0000
opened #0000
fixed #0000
and it will also close task
there is no mutitasking
or moving to columns

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
