### ISSUE TITLE
not appear setting fields at integration screen

### ISSUE THREAD

**Issue by rkyymmt** [kanboard/plugin-gitlab-webhook#11]
![2016-08-03 19 07 37](https://cloud.githubusercontent.com/assets/438621/17361930/ce9fd608-59ad-11e6-980e-f8c20e3f6f81.png)

**Comment by rkyymmt** [comment]
![2016-08-03 19 07 00](https://cloud.githubusercontent.com/assets/438621/17361983/09f07460-59ae-11e6-9867-a6276a26dcdf.png)

**Comment by michaeltlombardi** [comment]
@rkyymmt What was your solution for this? We're having the same exact problem.
