### ISSUE TITLE
all issues coming from gitlab are "unassigned" and have no owner

### ISSUE THREAD

**Issue by daudo** [kanboard/plugin-gitlab-webhook#12]
we have both the Gitlab Authentication and the Gitlab Webhook plugins installed and users are created automatically upon first login, but still all issues are listed as "unassigned" in kanboard.

Investigating the data sent by gitlab, I see this:
(
    [id] => 676
    [title] => debugging assignment
    [assignee_id] => 10
    [author_id] => 10
    [project_id] => 2
    [created_at] => 2016-08-24 15:12:15 UTC
    [updated_at] => 2016-08-24 15:12:15 UTC
    [position] => 0
    [branch_name] => 
    [description] => aha
    [milestone_id] => 
    [state] => opened
    [iid] => 9
    [updated_by_id] => 
    [confidential] => 
    [deleted_at] => 
    [moved_to_id] => 
    [due_date] => 
    [url] => https://ticktick.example.com/FooBar/testing/issues/9
    [action] => open
)

So gitlab sends both assignee_id and author_id to kanboard, but kanboard seems to ignore those values.

Interestingly, if I now comment such an issue in gitlab, the comment is correctly assigned to my account.

And if I look into the code, the user mapping seems to be there for the "handleCommentEvent", but for no other event.

... if I can fix it myself, a patch will follow shortly ...

**Comment by xenithorb** [comment]
I would still like to see this fixed. 

Could potentially be re-titled "Plugin does not assign task based on author_id or assignee_id"

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
