### ISSUE TITLE
Sync previous gitlab issues created

### ISSUE THREAD

**Issue by gpoudrel** [kanboard/plugin-gitlab-webhook#13]
When adding webhook to an existing project, it would be interesting to sync gitlab issues previously created with kanboard.

**Comment by Bzzz** [comment]
I second that, coming from the long-standing request at https://github.com/kanboard/kanboard/issues/1259

We need an import function to not scare away people with huge gitlab issue databases that need to be transferred sort of manually (read: loads of text editor magic) on a per-project basis into a new kanboard installation. Gitlab offers JSON exports - put it to good use.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
