### ISSUE TITLE
Got error when creating issues on GitLab Issue Opened

### ISSUE THREAD

**Issue by jerry1167** [kanboard/plugin-gitlab-webhook#14]
### My Application Versions
- Kanboard Application version: 1.0.33
- PHP version: 5.5.38
- OS version: Darwin 15.5.0
- Gitlab Webhook version : 1.0.4
- Gitlab version: 7.9.1
### Configuration Already
1. Copy 'Gitlab webhooks'  URL to Gitlab 'Web Hooks ' , and Test Hook success
2. Set project 'Automatic Actions' like this:

```
Event name = Gitlab issue opened
Action name = Create a task from an external provider
```
##### apache access_log get this issue opened POST request and returns 200 code

```
"POST /?controller=WebhookController&action=handler&plugin=GitlabWebhook&token=xxx&project_id=1 HTTP/1.1" 200 541
```
##### apache error_log got some ERROR :

```
[Mon Sep 26 15:21:39.476949 2016] [:error] [pid 44947] [client 192.168.4.214:28916] PHP Notice:  Undefined index: project in /Users/xxx/workspace/php-site/plugins/GitlabWebhook/WebhookHandler.php on line 165
[Mon Sep 26 15:21:39.477042 2016] [:error] [pid 44947] [client 192.168.4.214:28916] PHP Catchable fatal error:  Argument 2 passed to Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler::handleIssueOpened() must be of the type array, null given, called in /Users/xxx/workspace/php-site/plugins/GitlabWebhook/WebhookHandler.php on line 165 and defined in /Users/xxx/workspace/php-site/plugins/GitlabWebhook/WebhookHandler.php on line 183
```
##### None task been created on Kanboard .

Is this incompatible issues here ?  Or, just Gitlab webhook Interface and this plugin here not incompatible ?

**Comment by jerry1167** [comment]
Mine version Of Gitlab webhook request POST body like this:

```json
request: {
    "object_kind": "issue",
    "user": {
        "name": "xxx",
        "username": "xx",
        "avatar_url": "http://git.xxx.com/uploads/user/avatar/72/IMG_20120104_131515.jpg"
    },
    "object_attributes": {
        "id": 15286,
        "title": "total_execution_time",
        "assignee_id": 72,
        "author_id": 72,
        "project_id": 852,
        "created_at": "2016-09-26 08:52:43 UTC",
        "updated_at": "2016-09-26 08:52:43 UTC",
        "position": 0,
        "branch_name": null,
        "description": "total_execution_timetotal_execution_time",
        "milestone_id": null,
        "state": "opened",
        "iid": 11,
        "url": "http://git.xxx.com/xxxx/personal-mark/issues/11",
        "action": "open"
    }
}
```

None 'project' json body exist like this plugin test case fixtures.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
