### ISSUE TITLE
trigger resync?

### ISSUE THREAD

**Issue by jhnc** [kanboard/plugin-gitlab-webhook#15]
I have a gitlab project with 111 open issues.
It is linked to a kanboard project as per the configuration instructions.
However, the kanboard project only has 86 of the issues from gitlab.

Gitlab has been updated over time and is currently gitlab-ce 8.12.1-ce.0
Kanboard was 1.0.19 and is now 1.0.33
For a few days the GitlabWebhook plugin was not installed when kanboard was upgraded.

If kanboard is not running (or as here, the plugin isn't installed) and a gitlab webhook triggers, what happens?
Does gitlab keep retrying until kanboard+plugin is online, or is the event lost?

Is there a way to sync up kanboard with the current gitlab issue/comment state?

I notice that gitlab hooks page now shows an additional "Secret Token" field, which is not shown in the image included in the plugin's readme.

**Comment by fguillot** [comment]
According the the Gitlab documentation, Gitlab will retry to send the event if failed. But they don't specify the number of retries. So, I think the events are lost.

At the moment, this plugin is not able to import issues by using the Gitlab API, this feature is clearly missing.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
