### ISSUE TITLE
Add ability to assign category based on external label

### ISSUE THREAD

**Issue by hugopeek** [kanboard/plugin-gitlab-webhook#16]
This is already implemented in the Github webhook and is really convenient for automatically organizing your incoming tickets a little (especially when combined with the Assign color based on category action).

Could that be easily ported to work with the Gitlab webhook too, or does the API handle this differently?

**Comment by Pawamoy** [comment]
Indeed, I'm using the same columns in Gitlab's Board as the ones in my KanBoard project, so moving issues in GitLab would also move them in KanBoard (with a beautiful chain of automated actions haha: label -> category [-> color] -> column)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
