### ISSUE TITLE
where is the plugins directory?

### ISSUE THREAD

**Issue by bobweston** [kanboard/plugin-gitlab-webhook#18]
I'm using omnibus gitlab (version provisioned by the Puppet module). The application is installed here:

  /opt/gitlab/embedded/service/gitlab-rails

But I can't seem to find either the plugins directory or even the GitlabWebhook directory.

I've searched for it with this:

  ﻿﻿find / -xdev 2>/dev/null -name "plugins"

But the only thing remotely close is /opt/gitlab/embedded/lib/krb5/plugins

And that directory does not contain a GitlabWebhook directory.

Any thoughts? I'm hoping this isn't something obvious that I am missing.

Thanks for your help.

**Comment by fguillot** [comment]
The plugin directory is in your Kanboard folder hierarchy, not in Gitlab.
