### ISSUE TITLE
Broken link for attached files in issues

### ISSUE THREAD

**Issue by samjk1** [kanboard/plugin-gitlab-webhook#2]
I'm using the "Create a task from an external provider" and it works great, but if the user attaches a file to the issue in Gitlab the link in the description is broken.

The link URL is being created as (e.g.):
<pre>
(/uploads/eecd388fc1139048b57493070e9579a5/sample.docx)
</pre>
Instead of:
<pre>
(https://gitlabURL/projectName/uploads/eecd388fc1139048b57493070e9579a5/sample.docx)
</pre>

The same thing happens for comments.

**Comment by samjk1** [comment]
Thanks for creating kanboard & this plugin!

I changed the WebhookHandler.php file to:

<pre>
$event = array(
          ...
                'comment' => str_replace("/uploads", $payload['repository']['homepage']."/uploads",$payload['object_attributes']['note'])."\n\n[".t('By @%s on Gitlab', $payload['user']['username']).']('.$payload['object_attributes']['url'].')',
          ...
            );

</pre>

The "$payload['repository']['homepage']" contains the full URL for the gitlab, so adding this to handleCommentEvent and handleIssueOpened did it for me.

Ideally i'd add the URL only if it matches (/uploads.*).

**Comment by fguillot** [comment]
Relative links are now converted to absolute links. You can download the last version of this plugin.

Thanks.
