### ISSUE TITLE
Issue with  Github issue opened

### ISSUE THREAD

**Issue by kamov** [kanboard/plugin-gitlab-webhook#3]
```
Event name = Github issue opened
Action name = Create a task from an external provider
```

The assignes is not created.
username is the same, and this user is also connected with github account

**Comment by gpoudrel** [comment]
I confirm this issue is still here.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
