### ISSUE TITLE
correction chemin icone gitlab

### ISSUE THREAD

**Issue by xila76** [kanboard/plugin-gitlab-webhook#4]
Dans ./Template/project/integrations.php remplacement de la ligne 1 : 
`<h3><img src="<?= $this->url->dir() ?>plugins/GitlabWebhook/gitlab-icon.png"/>&nbsp;<?= t('Gitlab webhooks') ?></h3>`

par : 
`<h3><img src="<?php $this->url->dir() ?>plugins/GitlabWebhook/gitlab-icon.png"/>&nbsp;<?= t('Gitlab webhooks') ?></h3>`

sans cette correction le chemin vers l'image est : 
`<img src="//plugins/GitlabWebhook/gitlab-icon.png">`
après correction : 
`<img src="/plugins/GitlabWebhook/gitlab-icon.png">`

PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12)
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"

**Comment by fguillot** [comment]
This issue have been already fixed, you can download the version 1.0.2 of this plugin.
