### ISSUE TITLE
Question on two way sync with GitLab issues

### ISSUE THREAD

**Issue by divansantana** [kanboard/plugin-gitlab-webhook#5]
Hi @fguillot 

Quick question...

Does this project (and perhaps something else) allow for a two way sync with GitLab issues?

Because I've managed to get GitLab sending the events to Kanboard, Kanboard creates the tasks in the relevant Kanboard. However I'm not seeing how to get Kanboard to send the data to GitLab when one creates/modifies a task in Kanboard.

**Comment by fguillot** [comment]
This plugin is a one-way sync to Kanboard at the moment. The Gitlab API have to be implemented to support two-way sync.

**Comment by divansantana** [comment]
Ah ok. Thanks for the reply.

**Comment by brylie** [comment]
Are there any plans to implement Gitlab and Github APIs?

**Comment by brylie** [comment]
I.e. our team have a project on Github, but really desire an interface similar to Kanboard. We need to balance the fact that our sourcecode is located on Github, and that community members may continue to add Github issues. When we modify a Kanboard card, such as by labeling or replying, it would be important for those modifications to also show up on Github.

**Comment by stuartbuckell** [comment]
Hi guys,

It seems the API exists on Gitlab

https://docs.gitlab.com/ee/api/issues.html

New issue
POST /projects/:id/issues

**Comment by michaeltlombardi** [comment]
If this can be updated to include two-way sync, we're golden. ❤️

**Comment by divansantana** [comment]
@fguillot any chance there is a plan to address this in the near future? :crossed_fingers:

**Comment by fguillot** [comment]
I'm working on other improvements for Kanboard which are more important from my point of view. If I'm not fast enough, feel free to contribute, this is an open source software.

**Comment by iRynoh** [comment]
Hello, any updates on this?

**Comment by mbyakow** [comment]
If no one does work on this, I'll implement that feature. Please confirm.

**Comment by karanrajpal14** [comment]
@mbyakow please do. I'd love to have this as well. Would make our lives so much easier.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
