### ISSUE TITLE
Internal error 500 on webhook

### ISSUE THREAD

**Issue by folx** [kanboard/plugin-gitlab-webhook#6]
Hi there,

I'm trying to set-up Gitlab Webhook for the first time on a fresh Kanboard install. Plugin Directory get me 1.0.3 version. I created a new project, then add its integration URL to Gitlab Webhook, enabling events as listed in the gitlab-webhook readme.
When using hooks (either pressing the *test* button from webhook config or creating a new issue) from my Gitlab project, request led to a 500 error, with following PHP Fatal error in da webserver logs:

> Class 'Kanboard\Controller\Base' not found in /var/www/myDom/htdocs/plugins/GitlabWebhook/Controller/Webhook.php on line 15

Is there a Class path or alike to be set somewhere?
I'm using php 5.6.21 through a FastCGI/fpm backend.

Cheers,

**Comment by fguillot** [comment]
Do not mix Kanboard and plugin versions. Always use Kanboard stable version (1.0.28) with the stable plugin version (1.0.3).

The branch master of Kanboard is the development branch and plugins are not yet updated to reflect the latest changes.

**Comment by folx** [comment]
In deed, switching to git clone version of plugin-gitlab-webhook solves the problem.
Thank for the tip!
Is there any version tracking, somehow, to know which kanboard version the plugins expect?
