### ISSUE TITLE
move to another column if Gitlab commit received

### ISSUE THREAD

**Issue by esclkm** [kanboard/plugin-gitlab-webhook#7]
in our kanboard we have columns:
1/ to do
2/ work in progress
3/done

if task is done it should be tested by manager. and then manager will close the task

so we need on close task - to move it from one column to another

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
