### ISSUE TITLE
Issue with Gitlab issue opened

### ISSUE THREAD

**Issue by ickbinhier** [kanboard/plugin-gitlab-webhook#8]
if i create an new task from gitlab then i have in the fild Reference another count (90)
The link hase the count "/issues/89"

is this normal?

**Comment by fguillot** [comment]
The Gitlab Issue Id will be saved into the reference field of the Kanboard task, is it the answer to your question?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
